'use client';

interface ExportButtonsProps {
  profile: Record<string, unknown>;
}

function formatLevel(level: string): string {
  return level.replace('_', ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function ExportButtons({ profile }: ExportButtonsProps) {
  function downloadJson() {
    const blob = new Blob([JSON.stringify(profile, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `hazard-profile-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function downloadPdf() {
    const p = profile as any;
    const loc = p.location;
    const meta = p.meta;

    // Build a printable HTML document
    const hazardRows = (p.topRisks || [])
      .map(
        (h: any) =>
          `<tr>
            <td style="padding:8px;border-bottom:1px solid #e5e7eb">${h.type.replace('_', ' ').replace(/\b\w/g, (c: string) => c.toUpperCase())}</td>
            <td style="padding:8px;border-bottom:1px solid #e5e7eb;text-align:center;font-weight:bold">${h.score}/100</td>
            <td style="padding:8px;border-bottom:1px solid #e5e7eb">${formatLevel(h.level)}</td>
            <td style="padding:8px;border-bottom:1px solid #e5e7eb;font-size:12px">${h.description}</td>
          </tr>`,
      )
      .join('');

    const recItems = (p.recommendations || [])
      .map(
        (r: any) =>
          `<div style="margin-bottom:16px">
            <strong>${r.title}</strong> (${r.priority})
            <ul style="margin:4px 0 0 20px">${r.actionItems.map((a: string) => `<li style="margin:2px 0">${a}</li>`).join('')}</ul>
          </div>`,
      )
      .join('');

    const html = `<!DOCTYPE html>
<html><head><title>Hazard Risk Profile - ${loc.address}</title>
<style>
  body { font-family: -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #1f2937; }
  h1 { font-size: 24px; margin-bottom: 4px; }
  h2 { font-size: 18px; margin-top: 32px; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }
  .score { font-size: 64px; font-weight: 800; text-align: center; margin: 24px 0 8px; }
  .level { text-align: center; font-size: 18px; font-weight: 600; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; }
  th { text-align: left; padding: 8px; border-bottom: 2px solid #1f2937; font-size: 13px; text-transform: uppercase; }
  .meta { font-size: 12px; color: #9ca3af; margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 16px; }
  @media print { body { padding: 0; } }
</style></head><body>
<h1>Hazard Risk Profile</h1>
<p style="color:#6b7280">${loc.address}${loc.county ? ` &middot; ${loc.county} County, ${loc.state}` : ''}</p>
<div class="score">${p.overallScore}</div>
<div class="level">${formatLevel(p.overallLevel)} Risk</div>

<h2>Hazard Breakdown</h2>
<table>
  <thead><tr><th>Hazard</th><th style="text-align:center">Score</th><th>Level</th><th>Details</th></tr></thead>
  <tbody>${hazardRows}</tbody>
</table>

${recItems ? `<h2>Preparation Checklist</h2>${recItems}` : ''}

<div class="meta">
  <p>Assessed: ${new Date(meta.assessedAt).toLocaleString()} &middot; Engine: v${meta.engineVersion} &middot; Sources: ${meta.providersUsed.join(', ')}</p>
  <p>Generated by MyHazardProfile (https://github.com/sachinkg12/MyHazardProfile)</p>
  <p>Data from FEMA, USGS, NOAA, NIFC. For informational purposes only.</p>
</div>
</body></html>`;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.onload = () => {
        printWindow.print();
      };
    }
  }

  return (
    <div className="flex gap-2">
      <button
        onClick={downloadPdf}
        className="flex items-center gap-2 px-4 py-2 bg-white/20 border-2 border-white/40 rounded-xl hover:bg-white/30 transition-colors text-sm font-medium text-white"
        aria-label="Download risk profile as PDF"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        PDF
      </button>
      <button
        onClick={downloadJson}
        className="flex items-center gap-2 px-4 py-2 bg-white/20 border-2 border-white/40 rounded-xl hover:bg-white/30 transition-colors text-sm font-medium text-white"
        aria-label="Download risk profile as JSON"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        JSON
      </button>
    </div>
  );
}
